name: Android CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Nuke Color Picker Everywhere
      run: |
        # Gradle dosyalarından kütüphaneyi sil
        sed -i '/android-wear-color-picker/d' app/build.gradle || true
        sed -i '/android-wear-color-picker/d' build.gradle || true
        
        # Java kodlarından kütüphaneyi ve bağlı satırları temizle
        find app/src/main/java -type f -exec sed -i '/androidwearcolorpicker/d' {} + || true
        find app/src/main/java -type f -exec sed -i '/ColorPickerDialog/d' {} + || true

    - name: Build APK
      run: ./gradlew assembleDebug --continue

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pear-watch-face-apk
        path: '**/*.apk'
